POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "admin",
  "password": "d46ebefb7a8246ce59c9a6e6d3dc1a62074bb3405cc54565f05cebbb"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "newUser",
  "password": "d46ebefb7a8246ce59c9a6e6d3dc1a62074bb3405cc54565f05cebbb"
}
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "admin",
  "password": "d46ebefb7a8246ce59c9a6e6d3dc1a62074bb3405cc54565f05cebbb"
}
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "newUser",
  "password": "d46ebefb7a8246ce59c9a6e6d3dc1a62074bb3405cc54565f05cebbb"
}
###
POST http://localhost:3000/samples/list
Content-Type: application/json

{
  "token": "3459035945192e84b2949d17ebfc6b2fd9f71c7b02a0d4ccb2491fa"
}
###


POST http://localhost:3000/users/validate
Content-Type: application/json

{
  "token": "f6e5724e7c75f573624afa66d64fad3a943f8fc3ce3f532ff7aa5725"
}

###


POST http://localhost:3000/samples/new
Content-Type: application/json

{
  "token": "3f282e178acec9d29b23c43b499ccb2573321121106c48e01b1b1cf1",
  "sample": {
    "name": "Test",
    "pH": 7.0,
    "hardness": 100,
    "color": 0,
    "location": 0

  }
}

###

POST http://localhost:3000/samples/list
Content-Type: application/json

{
  "token": "3f282e178acec9d29b23c43b499ccb2573321121106c48e01b1b1cf1"
}

